use pizza;
select * from orders;
select * from order_details;
select * from pizza_types;
select * from pizzas;



-- CS1 : Extract only the table information
describe orders;
describe order_details;


-- CS2 : Total Revenue from All Orders
WITH CTE AS (SELECT 
		ORDER_ID, OD.PIZZA_ID, QUANTITY, PRICE, (QUANTITY * PRICE) AS TOTAL_PRICE
FROM 
    ORDER_DETAILS OD
LEFT JOIN PIZZAS P ON OD.PIZZA_ID = P.PIZZA_ID ) 
    SELECT 
		ROUND(SUM(TOTAL_PRICE),2) AS TOTAL_REVENUE
    FROM CTE;
    
    
    
-- CS3 : REVENUE BY PIZZA SIZE
SELECT 
    P.SIZE, 
    ROUND(SUM(P.PRICE * OD.QUANTITY),0) AS TOTAL_REVENUE
FROM ORDER_DETAILS OD 
LEFT JOIN PIZZAS P ON OD.PIZZA_ID = P.PIZZA_ID
GROUP BY 1
ORDER BY 2 DESC; 



-- CS4 : COUNT OF ORDERS BY DAY
WITH CTE AS (SELECT
        DATE, 
        COUNT(ORDER_ID) AS DAILY_SALES,
        RANK() OVER (ORDER BY COUNT(ORDER_ID) DESC) AS RN
        FROM ORDERS
        GROUP BY 1)
SELECT * 
FROM CTE;


-- CS45 : COUNT OF ORDERS IN DECEMBER
SELECT 
	SUM(IDS) AS TOTAL_ORDERS_IN_DECEMBER 
FROM  
	(SELECT 
		DATE,
        COUNT(ORDER_ID) AS IDS
	FROM ORDERS 
	WHERE STR_TO_DATE(date, '%Y-%m-%d')  BETWEEN '2015-12-01' AND '2015-12-30' 
	GROUP BY 1) X ;
    

-- CS6 : MONTHLY PIZZA SALES
WITH M_P_S AS (
    SELECT 
		STR_TO_DATE(date, '%Y-%m-%d') AS DAYS, 
		ORDER_ID, 
		TIME
    FROM ORDERS) 
SELECT 
	EXTRACT(MONTH FROM DAYS) AS MONTH, 
	COUNT(ORDER_ID) AS TOTAL_ORDERS
FROM M_P_S 
GROUP BY 1
ORDER BY 1, 2 DESC;



-- CS7 : ORDER BY TIME OF A DAY (MORNING, AFTERNOON, EVENING)
WITH M_A_E AS (
    SELECT 
		HOUR(STR_TO_DATE(TIME, '%H:%i:%s')) AS TIMESS, 
        ORDER_ID
    FROM ORDERS)
SELECT 
    CASE
		WHEN TIMESS BETWEEN 0 AND 11 THEN 'MORNING'
        WHEN TIMESS BETWEEN 12 AND 17 THEN 'AFTERNOON'
        WHEN TIMESS BETWEEN 18 AND 23 THEN 'EVENING'
	END AS TIME_OF_THE_DAY,
    COUNT(ORDER_ID) AS TOTAL_ORDERS
FROM M_A_E
GROUP BY 1
ORDER BY 2 DESC;








